spring.application.name=spring-security

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000

spring.security.oauth2.resourceserver.jwt.audiences=https://spring-security-api
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-iamssa85wl4jrzqy.us.auth0.com/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
